data_module:
  _target_: ../..
  train:
    batch_size: 
    shuffle: True
    num_workers: 
    drop_last: False
    pin_memory: True
    collate_fn: null
  val:
    batch_size: ${train.batch_size}
    shuffle: False
    num_workers: ${train.num_workers}
    drop_last: False
    pin_memory: True
    collate_fn: null
  test:
    batch_size: ${train.batch_size}
    shuffle: False
    num_workers: ${train.num_workers}
    drop_last: False
    pin_memory: True
    collate_fn: null