_target_: datasets.omc_pl_module.OMCModule
train:
  batch_size: 8
  shuffle: True
  num_workers: 2
  drop_last: False
  pin_memory: True
  collate_fn: null
val:
  batch_size: 8
  shuffle: False
  num_workers: 2
  drop_last: False
  pin_memory: True
  collate_fn: null
test:
  batch_size: 8
  shuffle: False
  num_workers: 2
  drop_last: False
  pin_memory: True
  collate_fn: null