train:
  _target_: datasets.omc.OMC
  data_dir: ${hydra:runtime.cwd}/data
  transform: null
val:
  _target_: datasets.omc.OMC_Test
  data_dir: ${hydra:runtime.cwd}/data
  transform: null
test: 
  _target_: datasets.omc.OMC_Test
  data_dir: ${hydra:runtime.cwd}/data
  transform: null